from day8 import (
    AntennaMap,
    HarmonicAntennaMap,
    part_two,
    part_one,
)


test_string = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""


amap = AntennaMap(test_string)
print(part_one(amap))
hamap = HarmonicAntennaMap(test_string)
print(f"part two: {part_two(hamap)}")
